1

   Abaqus 2022                                  Date 22-Sep-2026   Time 17:21:03
   For use by Supplied by Team-SolidSQUAD under license from Dassault Systemes or its subsidiary.

                                                                                 
                                                                                 
 STEP    1     INCREMENT     1     STEP TIME    0.00    


                        A N A L Y S I S    D A T A C H E C K




                        S T E P       1     C O N S O L I D A T I O N   A N A L Y S I S


                                                                                          
          MAX. PORE PRESSURE CHANGE PERMITTED IN AN INC.       1.000E+03
          A SUGGESTED INITIAL TIME INCREMENT OF                1.000E-04
          AND A TOTAL TIME PERIOD OF                           1.000E+09
          THE MINIMUM TIME INCREMENT ALLOWED IS                1.000E-10
          THE MAXIMUM TIME INCREMENT ALLOWED IS                1.000E+07



          CREEP, SWELLING, AND VISCOELASTIC EFFECTS ARE OMITTED IN THIS STEP
          THE ANALYSIS WILL TERMINATE AT THE FINAL TIME SPECIFIED
          OR WHEN THE RATE OF CHANGE OF PORE PRESSURE FALLS BELOW   1.000E-06

 ***WARNING: THERE ARE 99 UNCONNECTED REGIONS IN THE MODEL.

     COLLECTING MODEL CONSTRAINT INFORMATION FOR OVERCONSTRAINT CHECKS

     COLLECTING STEP CONSTRAINT INFORMATION FOR OVERCONSTRAINT CHECKS



     JOB TIME SUMMARY
       USER TIME (SEC)      =   67.100    
       SYSTEM TIME (SEC)    =   5.8000    
       TOTAL CPU TIME (SEC) =   72.900    
       WALLCLOCK TIME (SEC) =         93
