#!/usr/bin/env python3
"""Create a v14 INP from the converged v13 baseline without overwriting v13.

Only source-supported hydraulic tailwater heads are changed. Geometry,
materials, ties, geostatic setup and the v13 rigid-body cleanup are preserved.
No CAE file is claimed/generated by this pure-Python script.
"""
from __future__ import annotations
import argparse
import collections
import csv
import os
import re
import sys

HERE=os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path: sys.path.insert(0,HERE)
from repair_v12_3d import parse_deck, global_coord, WATER_UNIT_WEIGHT

TARGETS={
    "S03_NORMAL_RESERVOIR_3076M": (3076.00,3053.50,"normal stability case"),
    "S04_DESIGN_FLOOD_3580CMS": (3076.00,3060.26,"explicit design-flood stability case"),
    "S05_CHECK_FLOOD_AND_SEISMIC": (3077.35,3061.38,"check-flood stability case"),
    "S06_DRAWDOWN_TO_3074M": (3074.00,3053.50,"dead-water/drawdown stability case"),
}

def fmt(v): return "%.10g"%float(v)

def parse_downstream_sets(lines, parts, instances):
    imap=dict(instances)
    sets={}
    active=None
    for line in lines:
        s=line.strip()
        m=re.match(r"\*Nset,\s*nset=(V12_D_\d+),\s*instance=([^,]+)",s,re.I)
        if m:
            active=(m.group(1),m.group(2)); sets[active[0]]={"instance":active[1],"labels":[]}; continue
        if active and s.startswith("*"):
            active=None
        elif active and s and not s.startswith("**"):
            for token in s.split(","):
                token=token.strip()
                if token:
                    try: sets[active[0]]["labels"].append(int(token))
                    except ValueError: pass
    for name,row in sets.items():
        inst=row["instance"]; part=imap[inst]
        if not row["labels"]: raise RuntimeError("empty downstream set %s"%name)
        # v12 builder created one-node downstream sets; support >1 conservatively.
        zs=[]
        for label in row["labels"]:
            coord=parts[part]["nodes"][label]
            zs.append(global_coord(inst,part,coord)[2])
        if max(zs)-min(zs)>1e-6:
            raise RuntimeError("downstream set %s spans multiple elevations"%name)
        row["z"]=sum(zs)/len(zs)
    return sets

def main():
    ap=argparse.ArgumentParser(); ap.add_argument("source_v13_inp"); ap.add_argument("output_v14_inp"); ap.add_argument("audit_csv"); args=ap.parse_args()
    lines,parts,instances,_=parse_deck(args.source_v13_inp)
    dsets=parse_downstream_sets(lines,parts,instances)
    if not dsets: raise SystemExit("No V12_D_* downstream node sets found")
    out=[]; current_step=None; records=[]; replacements=collections.Counter()
    inserted_header=False
    for line in lines:
        s=line.strip()
        m=re.match(r"\*Step,\s*name=([^,]+)",s,re.I)
        if m: current_step=m.group(1)
        if not inserted_header and not s.startswith("**"):
            out.extend(["** V14 DESIGN ALIGNMENT: v13 geometry/mechanics preserved.","** Tailwater heads corrected from project stability-condition table; v13 is not overwritten."])
            inserted_header=True
        fields=[v.strip() for v in s.split(",")]
        if current_step in TARGETS and len(fields)>=4 and fields[0] in dsets:
            try: dof1=int(fields[1]); dof2=int(fields[2]); old=float(fields[3])
            except ValueError: dof1=dof2=-1
            if dof1==8 and dof2==8:
                z=dsets[fields[0]]["z"]; hd=TARGETS[current_step][1]
                new=WATER_UNIT_WEIGHT*max(hd-z,0.0)
                line="%s, 8, 8, %s"%(fields[0],fmt(new))
                records.append([current_step,fields[0],z,old,new,hd,TARGETS[current_step][2]])
                replacements[current_step]+=1
        out.append(line)
    missing=[s for s in TARGETS if replacements[s]==0]
    if missing: raise RuntimeError("No downstream BC replacements in steps: %s"%", ".join(missing))
    os.makedirs(os.path.dirname(os.path.abspath(args.output_v14_inp)),exist_ok=True)
    with open(args.output_v14_inp,"w",encoding="utf-8",newline="\n") as h: h.write("\n".join(out)+"\n")
    with open(args.audit_csv,"w",encoding="utf-8",newline="") as h:
        w=csv.writer(h); w.writerow(["step","nset","node_z_m","old_p_kPa","new_p_kPa","target_downstream_head_m","basis"])
        for r in records: w.writerow([r[0],r[1],"%.6f"%r[2],"%.6f"%r[3],"%.6f"%r[4],"%.2f"%r[5],r[6]])
    print("V14_WRITTEN",args.output_v14_inp)
    for step in TARGETS: print(step,"replacements",replacements[step],"tailwater",TARGETS[step][1])

if __name__=="__main__": main()
