1

   Abaqus 2022                                  Date 17-Sep-2026   Time 19:50:20
   For use by Supplied by Team-SolidSQUAD under license from Dassault Systemes or its subsidiary.

                                                                                 
                                                                                 
 STEP    1     INCREMENT     1     STEP TIME    0.00    


                        A N A L Y S I S    D A T A C H E C K




                        S T E P       1     G E O S T A T I C   S T R E S S   A N A L Y S I S


                                                                                          

     AUTOMATIC TIME CONTROL WITH -
          A SUGGESTED INITIAL TIME INCREMENT OF                 1.00    
          AND A TOTAL TIME PERIOD OF                            1.00    
          THE MINIMUM TIME INCREMENT ALLOWED IS                1.000E-05
          THE MAXIMUM TIME INCREMENT ALLOWED IS                 1.00    

 ***WARNING: THERE ARE 4 UNCONNECTED REGIONS IN THE MODEL.

     COLLECTING MODEL CONSTRAINT INFORMATION FOR OVERCONSTRAINT CHECKS

     COLLECTING STEP CONSTRAINT INFORMATION FOR OVERCONSTRAINT CHECKS



     JOB TIME SUMMARY
       USER TIME (SEC)      =   8.5000    
       SYSTEM TIME (SEC)    =  0.70000    
       TOTAL CPU TIME (SEC) =   9.2000    
       WALLCLOCK TIME (SEC) =          9
